# This file was fully implemented by AI.
#
# Function:
#   Build a planar conformal parameterization for closed triangle meshes.
#   For genus-zero meshes it creates a disk by cutting a short slit (or falls
#   back to a vertex-star cut if needed). For positive genus meshes it constructs
#   a short homology-based cut graph, connects it if necessary, cuts the mesh by
#   duplicating seam vertices without deleting faces, checks that the result is
#   one topological disk, and solves LSCM using EC = ED - A with two fixed
#   vertices. It also saves UV arrays and UV visualizations with wireframe,
#   Laplacian-magnitude coloring, and quadrant coloring.
#
# Difference from 02-conformal-mapping.py:
#   02-conformal-mapping.py is only a simple spectral embedding using
#   eigenvectors of the cotangent Laplacian as 2D coordinates. It does not cut
#   closed high-genus surfaces, does not guarantee a disk topology, and does not
#   solve the LSCM conformal energy. This file implements the full cut + LSCM pipeline.

from collections import defaultdict, deque
from pathlib import Path
import heapq
import math

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection
import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spla

from closed_surface import ClosedSurface


INPUT_DIR = Path("input")
OUTPUT_DIR = Path("output_lscm")
MAX_LANDMARKS = 96
DEFAULT_GENERA = {0}
GENUS_ZERO_SLIT_FRACTION = 0.6


def undirected_edges(faces):
    """Build unique undirected edges and the incident-face list of each edge."""
    edges = {}
    edge_faces = defaultdict(list)
    for fi, (a, b, c) in enumerate(faces):
        for u, v in ((a, b), (b, c), (c, a)):
            e = (int(min(u, v)), int(max(u, v)))
            if e not in edges:
                edges[e] = len(edges)
            edge_faces[e].append(fi)
    return edges, edge_faces


def mesh_genus(verts, faces):
    """Return genus and Euler data for a closed triangle mesh."""
    edges, edge_faces = undirected_edges(faces)
    boundary_edges = [e for e, fs in edge_faces.items() if len(fs) == 1]
    chi = len(verts) - len(edges) + len(faces)
    if boundary_edges:
        return None, chi, len(edges), boundary_edges
    return (2 - chi) // 2, chi, len(edges), boundary_edges


def edge_lengths(verts, edges):
    """Compute Euclidean edge lengths."""
    return {e: float(np.linalg.norm(verts[e[0]] - verts[e[1]])) for e in edges}


def adjacency_from_edges(n, lengths):
    """Build a weighted vertex adjacency list from an edge-length dictionary."""
    adj = [[] for _ in range(n)]
    for (u, v), w in lengths.items():
        adj[u].append((v, w))
        adj[v].append((u, w))
    return adj


def dijkstra_tree(adj, root):
    """Compute one shortest-path tree from a root."""
    n = len(adj)
    dist = np.full(n, np.inf)
    parent = np.full(n, -1, dtype=np.int64)
    parent_edge = [None] * n
    dist[root] = 0.0
    heap = [(0.0, root)]
    while heap:
        d, u = heapq.heappop(heap)
        if d != dist[u]:
            continue
        for v, w in adj[u]:
            nd = d + w
            if nd < dist[v]:
                dist[v] = nd
                parent[v] = u
                parent_edge[v] = (min(u, v), max(u, v))
                heapq.heappush(heap, (nd, v))
    return dist, parent, parent_edge


def path_to_root(v, parent):
    """Return the tree path from a vertex to the root."""
    path = []
    while v != -1:
        path.append(int(v))
        v = int(parent[v])
    return path


def fundamental_cycle(u, v, parent):
    """Return the shortest-tree fundamental cycle generated by edge (u, v)."""
    pu = path_to_root(u, parent)
    pv = path_to_root(v, parent)
    pos = {x: i for i, x in enumerate(pu)}
    lca = None
    j_lca = None
    for j, x in enumerate(pv):
        if x in pos:
            lca = x
            j_lca = j
            break
    return pu[:pos[lca] + 1] + pv[:j_lca][::-1]


def cycle_edges(cycle):
    """Convert a cyclic vertex list into undirected edges."""
    out = []
    for i in range(len(cycle)):
        u = cycle[i]
        v = cycle[(i + 1) % len(cycle)]
        if u != v:
            out.append((min(u, v), max(u, v)))
    return out


def gf2_insert(basis, x):
    """Insert a bit-vector into a GF(2) row-echelon basis."""
    y = x
    while y:
        p = y.bit_length() - 1
        if p in basis:
            y ^= basis[p]
        else:
            basis[p] = y
            return True
    return False


def gf2_reduce(basis, x):
    """Reduce a bit-vector by a GF(2) row-echelon basis."""
    y = x
    while y:
        p = y.bit_length() - 1
        if p not in basis:
            return y
        y ^= basis[p]
    return 0


def chain_bits(edges, edge_to_index):
    """Encode a mod-2 edge chain as one Python integer bitset."""
    x = 0
    for e in edges:
        x ^= 1 << edge_to_index[e]
    return x


def boundary_basis_mod2(faces, edge_to_index):
    """Build the GF(2) span of triangle boundaries."""
    basis = {}
    for a, b, c in faces:
        es = [
            (min(int(a), int(b)), max(int(a), int(b))),
            (min(int(b), int(c)), max(int(b), int(c))),
            (min(int(c), int(a)), max(int(c), int(a))),
        ]
        gf2_insert(basis, chain_bits(es, edge_to_index))
    return basis


def farthest_landmark_roots(adj, k):
    """Choose landmark roots by farthest-point sampling on graph distance."""
    roots = [0]
    best = None
    for _ in range(1, k):
        dist, _, _ = dijkstra_tree(adj, roots[-1])
        best = dist if best is None else np.minimum(best, dist)
        roots.append(int(np.argmax(best)))
    return roots


def shortest_homology_basis(verts, faces, genus):
    """Approximate a shortest homology basis using many shortest-path trees."""
    edge_to_index, _ = undirected_edges(faces)
    lengths = edge_lengths(verts, edge_to_index.keys())
    adj = adjacency_from_edges(len(verts), lengths)
    roots = farthest_landmark_roots(adj, min(len(verts), MAX_LANDMARKS))
    boundary_basis = boundary_basis_mod2(faces, edge_to_index)
    selected_basis = dict(boundary_basis)
    candidates = []

    for root in roots:
        dist, parent, parent_edge = dijkstra_tree(adj, root)
        tree_edges = {e for e in parent_edge if e is not None}
        for e in lengths:
            if e in tree_edges:
                continue
            u, v = e
            if not np.isfinite(dist[u]) or not np.isfinite(dist[v]):
                continue
            cycle = fundamental_cycle(u, v, parent)
            if len(cycle) < 3:
                continue
            es = cycle_edges(cycle)
            bits = chain_bits(es, edge_to_index)
            if gf2_reduce(boundary_basis, bits) == 0:
                continue
            candidates.append((sum(lengths[x] for x in es), cycle, es, bits))

    candidates.sort(key=lambda x: x[0])
    basis = []
    seen = set()
    for length, cycle, es, bits in candidates:
        if gf2_reduce(selected_basis, bits) == 0:
            continue
        key = frozenset(es)
        if key in seen:
            continue
        seen.add(key)
        gf2_insert(selected_basis, bits)
        basis.append({"length": length, "vertices": cycle, "edges": es})
        if len(basis) == 2 * genus:
            break

    if len(basis) != 2 * genus:
        raise RuntimeError("failed to find a full shortest homology basis")
    return basis


def cut_graph_components(cut_edges):
    """Return connected components of the cut graph."""
    adj = defaultdict(set)
    for u, v in cut_edges:
        adj[u].add(v)
        adj[v].add(u)
    unseen = set(adj)
    comps = []
    while unseen:
        s = unseen.pop()
        q = deque([s])
        comp = {s}
        while q:
            u = q.popleft()
            for v in adj[u]:
                if v in unseen:
                    unseen.remove(v)
                    comp.add(v)
                    q.append(v)
        comps.append(comp)
    return comps


def shortest_path_between_vertex_sets(adj, sources, targets):
    """Find the shortest mesh-edge path connecting two vertex sets."""
    target_set = set(targets)
    dist = {}
    parent = {}
    heap = []
    for s in sources:
        dist[s] = 0.0
        parent[s] = None
        heapq.heappush(heap, (0.0, s))
    hit = None
    while heap:
        d, u = heapq.heappop(heap)
        if d != dist[u]:
            continue
        if u in target_set:
            hit = u
            break
        for v, w in adj[u]:
            nd = d + w
            if nd < dist.get(v, np.inf):
                dist[v] = nd
                parent[v] = u
                heapq.heappush(heap, (nd, v))
    if hit is None:
        raise RuntimeError("cut graph components cannot be connected")
    path = []
    u = hit
    while u is not None:
        path.append(u)
        u = parent[u]
    path.reverse()
    return [(min(path[i], path[i + 1]), max(path[i], path[i + 1])) for i in range(len(path) - 1)]


def make_connected_cut_graph(verts, edges, cut_edges):
    """Connect disjoint homology cycles by shortest mesh paths."""
    lengths = edge_lengths(verts, edges)
    adj = adjacency_from_edges(len(verts), lengths)
    cut_edges = set(cut_edges)
    while True:
        comps = cut_graph_components(cut_edges)
        if len(comps) <= 1:
            return cut_edges
        base = comps[0]
        best = None
        for comp in comps[1:]:
            path = shortest_path_between_vertex_sets(adj, base, comp)
            length = sum(lengths[e] for e in path)
            if best is None or length < best[0]:
                best = (length, path)
        cut_edges.update(best[1])


def vertex_incident_faces(faces):
    """Collect incident faces for every vertex."""
    incident = defaultdict(list)
    for fi, tri in enumerate(faces):
        for v in tri:
            incident[int(v)].append(fi)
    return incident


def incident_face_components_at_vertex(v, incident_faces, faces, cut_edges):
    """Split incident faces around one vertex across cut edges."""
    local = defaultdict(set)
    for f in incident_faces:
        local[f]
    edge_to_local_faces = defaultdict(list)
    for f in incident_faces:
        tri = faces[f]
        for a, b in ((tri[0], tri[1]), (tri[1], tri[2]), (tri[2], tri[0])):
            if int(a) == v or int(b) == v:
                e = (min(int(a), int(b)), max(int(a), int(b)))
                edge_to_local_faces[e].append(f)
    for e, fs in edge_to_local_faces.items():
        if e in cut_edges or len(fs) != 2:
            continue
        f0, f1 = fs
        local[f0].add(f1)
        local[f1].add(f0)

    comps = []
    unseen = set(incident_faces)
    while unseen:
        s = unseen.pop()
        q = deque([s])
        comp = {s}
        while q:
            f = q.popleft()
            for g in local[f]:
                if g in unseen:
                    unseen.remove(g)
                    comp.add(g)
                    q.append(g)
        comps.append(comp)
    return comps


def cut_mesh(verts, faces, cut_edges):
    """Cut a mesh by duplicating seam vertices while keeping all faces."""
    cut_edges = set(cut_edges)
    incident = vertex_incident_faces(faces)
    new_verts = []
    new_to_old = []
    face_vertex_copy = {}
    old_to_copies = defaultdict(list)
    for v in range(len(verts)):
        comps = incident_face_components_at_vertex(v, incident[v], faces, cut_edges)
        for comp in comps:
            nv = len(new_verts)
            new_verts.append(verts[v])
            new_to_old.append(v)
            old_to_copies[v].append(nv)
            for f in comp:
                face_vertex_copy[(f, v)] = nv

    new_faces = np.empty_like(faces)
    for fi, tri in enumerate(faces):
        for k, v in enumerate(tri):
            new_faces[fi, k] = face_vertex_copy[(fi, int(v))]
    return np.asarray(new_verts, dtype=np.float64), new_faces, np.asarray(new_to_old), old_to_copies


def genus_zero_cut_edges(verts, faces):
    """Create a one-vertex puncture for a genus-zero closed mesh."""
    incident = vertex_incident_faces(faces)
    center = np.mean(verts, axis=0)
    score = np.linalg.norm(verts - center, axis=1)
    v = int(np.argmax(score))
    return {(min(v, int(u)), max(v, int(u))) for f in incident[v] for u in faces[f] if int(u) != v}


def genus_zero_slit_cut_edges(verts, faces, length_fraction=GENUS_ZERO_SLIT_FRACTION):
    """Create a short slit starting at the farthest-from-center vertex."""
    all_edges, _ = undirected_edges(faces)
    lengths = edge_lengths(verts, all_edges.keys())
    adj = adjacency_from_edges(len(verts), lengths)
    center = np.mean(verts, axis=0)
    start = int(np.argmax(np.linalg.norm(verts - center, axis=1)))
    target = int(np.argmin(np.dot(verts - center, verts[start] - center)))
    dist, parent, _ = dijkstra_tree(adj, start)
    if parent[target] == -1:
        return genus_zero_cut_edges(verts, faces), [start]

    target_length = length_fraction * np.linalg.norm(np.ptp(verts, axis=0))
    path = [target]
    while path[-1] != start:
        path.append(int(parent[path[-1]]))
    path.reverse()

    cut_edges = set()
    path_vertices = [path[0]]
    travelled = 0.0
    for u, v in zip(path, path[1:]):
        e = (min(u, v), max(u, v))
        cut_edges.add(e)
        path_vertices.append(v)
        travelled += lengths[e]
        if travelled >= target_length:
            break

    if not cut_edges:
        return genus_zero_cut_edges(verts, faces), [start]
    return cut_edges, path_vertices


def boundary_loops(faces):
    """Extract oriented boundary loops from a triangle mesh."""
    directed = defaultdict(int)
    undirected_count = defaultdict(int)
    for a, b, c in faces:
        for u, v in ((int(a), int(b)), (int(b), int(c)), (int(c), int(a))):
            directed[(u, v)] += 1
            undirected_count[(min(u, v), max(u, v))] += 1
    boundary_halfedges = []
    for u, v in directed:
        if undirected_count[(min(u, v), max(u, v))] == 1:
            boundary_halfedges.append((u, v))
    nxt = {u: v for u, v in boundary_halfedges}
    loops = []
    unused = set(nxt)
    while unused:
        start = unused.pop()
        loop = [start]
        u = start
        while True:
            v = nxt[u]
            if v == start:
                break
            loop.append(v)
            unused.remove(v)
            u = v
        loops.append(loop)
    return loops


def count_components(n, faces):
    """Count connected components in the mesh vertex graph."""
    adj = [[] for _ in range(n)]
    for a, b, c in faces:
        for u, v in ((a, b), (b, c), (c, a)):
            adj[int(u)].append(int(v))
            adj[int(v)].append(int(u))
    seen = np.zeros(n, dtype=bool)
    comps = 0
    for s in range(n):
        if seen[s]:
            continue
        comps += 1
        q = deque([s])
        seen[s] = True
        while q:
            u = q.popleft()
            for v in adj[u]:
                if not seen[v]:
                    seen[v] = True
                    q.append(v)
    return comps


def disk_checks(verts, faces):
    """Return Euler characteristic, component count, and boundary loops."""
    edges, _ = undirected_edges(faces)
    loops = boundary_loops(faces)
    chi = len(verts) - len(edges) + len(faces)
    comps = count_components(len(verts), faces)
    return chi, comps, loops


def cotangent(a, b, c):
    """Compute cot(angle bac)."""
    ba = b - a
    ca = c - a
    return float(np.dot(ba, ca) / (np.linalg.norm(np.cross(ba, ca)) + 1e-14))


def cotan_stiffness(verts, faces):
    """Assemble the 1/2 <Delta z, z> cotangent stiffness matrix."""
    n = len(verts)
    rows = []
    cols = []
    vals = []

    def add(i, j, v):
        rows.append(i)
        cols.append(j)
        vals.append(v)

    for a, b, c in faces:
        a, b, c = int(a), int(b), int(c)
        for i, j, k in ((b, c, a), (c, a, b), (a, b, c)):
            w = 0.25 * cotangent(verts[k], verts[i], verts[j])
            add(i, i, w)
            add(j, j, w)
            add(i, j, -w)
            add(j, i, -w)
    Q = sp.coo_matrix((vals, (rows, cols)), shape=(n, n)).tocsr()
    return 0.5 * (Q + Q.T)


def lscm_matrix(verts, faces, boundary):
    """Assemble the real block matrix for EC = ED - A."""
    n = len(verts)
    Q = cotan_stiffness(verts, faces)
    rows = []
    cols = []
    vals = []
    for t, i in enumerate(boundary):
        j = boundary[(t + 1) % len(boundary)]
        rows.extend([i, j])
        cols.extend([j, i])
        vals.extend([-0.25, 0.25])
    B = sp.coo_matrix((vals, (rows, cols)), shape=(n, n)).tocsr()
    return sp.bmat([[Q, B], [B.T, Q]], format="csr")


def solve_lscm(verts, faces, boundary):
    """Solve LSCM with z(p0)=0 and z(p1)=1 constraints."""
    n = len(verts)
    K = lscm_matrix(verts, faces, boundary).tocsr()
    p0 = boundary[0]
    lengths = np.linalg.norm(verts[boundary] - verts[p0], axis=1)
    p1 = boundary[int(np.argmax(lengths))]
    fixed = np.array([p0, p1, n + p0, n + p1], dtype=np.int64)
    fixed_values = np.array([0.0, 1.0, 0.0, 0.0], dtype=np.float64)
    free = np.setdiff1d(np.arange(2 * n), fixed)
    A = K[free][:, free]
    rhs = -(K[free][:, fixed] @ fixed_values)
    if A.shape[0] > 20000:
        sol_free = spla.lsmr(A, rhs, atol=1e-9, btol=1e-9, maxiter=30000)[0]
    else:
        sol_free = spla.spsolve(A, rhs)
    x = np.zeros(2 * n, dtype=np.float64)
    x[fixed] = fixed_values
    x[free] = sol_free
    return np.column_stack([x[:n], x[n:]]), (p0, p1)


def blue_gray_red(t):
    """Map a scalar in [-1, 1] to the blue-gray-red palette used in the exercises."""
    t = float(np.clip(t, -1.0, 1.0))
    gray = np.array([0.72, 0.72, 0.72])
    blue = np.array([0.12, 0.25, 0.95])
    red = np.array([0.95, 0.12, 0.08])
    if t < 0:
        a = -t
        return (1 - a) * gray + a * blue
    return (1 - t) * gray + t * red


def laplacian_vectors(verts, faces):
    """Compute cotangent-Laplacian vectors by one pass over all faces."""
    n = len(verts)
    vectors = np.zeros((n, 3), dtype=np.float64)
    weights = defaultdict(float)
    for a, b, c in faces:
        a, b, c = int(a), int(b), int(c)
        for i, j, k in ((b, c, a), (c, a, b), (a, b, c)):
            e = (min(i, j), max(i, j))
            weights[e] += 0.5 * cotangent(verts[k], verts[i], verts[j])
    for (i, j), w in weights.items():
        vectors[i] += w * (verts[j] - verts[i])
        vectors[j] += w * (verts[i] - verts[j])
    return vectors


def laplacian_magnitude_colors(verts, faces):
    """Color vertices by the signed Laplacian scale used in chapter 1."""
    laplacians = laplacian_vectors(verts, faces)

    vertex_normals = np.zeros_like(verts)
    for f in faces:
        i, j, k = (int(x) for x in f)
        normal = np.cross(verts[j] - verts[i], verts[k] - verts[i])
        normal /= np.linalg.norm(normal) + 1e-12
        vertex_normals[[i, j, k]] += normal
    vertex_normals /= np.linalg.norm(vertex_normals, axis=1, keepdims=True) + 1e-12

    scale = np.linalg.norm(laplacians, axis=1)
    scale[np.einsum("ij,ij->i", laplacians, vertex_normals) < 0] *= -1
    normed_scale = scale / (np.abs(scale).max() + 1e-14)
    return np.array([blue_gray_red(t) for t in normed_scale], dtype=np.float32)


def quadrant_colors(verts):
    """Color vertices by the signs of x, y, and z coordinates."""
    palette = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
        [1.0, 1.0, 0.0],
        [1.0, 0.0, 1.0],
        [0.0, 1.0, 1.0],
        [1.0, 0.5, 0.0],
        [0.5, 0.5, 0.5],
    ])
    x_sign = (verts[:, 0] >= 0).astype(int)
    y_sign = (verts[:, 1] >= 0).astype(int)
    z_sign = (verts[:, 2] >= 0).astype(int)
    return palette[x_sign * 4 + y_sign * 2 + z_sign]


def save_uv_image(uv, faces, path, vertex_colors=None):
    """Save one UV visualization, optionally with per-vertex colors."""
    fig, ax = plt.subplots(figsize=(7, 7))
    if vertex_colors is None:
        ax.triplot(uv[:, 0], uv[:, 1], faces, lw=0.25, color="black")
    else:
        polys = uv[faces]
        face_colors = vertex_colors[faces].mean(axis=1)
        collection = PolyCollection(
            polys,
            facecolors=face_colors,
            edgecolors=(0.0, 0.0, 0.0, 0.18),
            linewidths=0.12,
        )
        ax.add_collection(collection)
        ax.autoscale_view()
    ax.set_aspect("equal", adjustable="box")
    ax.axis("off")
    fig.tight_layout(pad=0)
    fig.savefig(path, dpi=240)
    plt.close(fig)


def save_all_outputs(name, uv, faces, new_to_old, lap_colors, quad_colors):
    """Save UV arrays and every requested visualization."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    np.save(OUTPUT_DIR / f"{name}_uv.npy", uv)
    np.save(OUTPUT_DIR / f"{name}_faces.npy", faces)
    save_uv_image(uv, faces, OUTPUT_DIR / f"{name}_uv_wire.png")
    save_uv_image(uv, faces, OUTPUT_DIR / f"{name}_uv_laplacian.png", lap_colors[new_to_old])
    save_uv_image(uv, faces, OUTPUT_DIR / f"{name}_uv_quadrant.png", quad_colors[new_to_old])


def build_cut_disk(verts, faces, genus):
    """Build a disk mesh by cutting genus-zero or positive-genus closed meshes."""
    if genus == 0:
        cut_edges, path_vertices = genus_zero_slit_cut_edges(verts, faces)
        basis = []
    else:
        path_vertices = []
        basis = shortest_homology_basis(verts, faces, genus)
        cut_edges = set()
        for cycle in basis:
            cut_edges.update(cycle["edges"])
        all_edges, _ = undirected_edges(faces)
        cut_edges = make_connected_cut_graph(verts, all_edges.keys(), cut_edges)
    cut_verts, cut_faces, new_to_old, _ = cut_mesh(verts, faces, cut_edges)
    return cut_verts, cut_faces, new_to_old, basis, path_vertices


def process_mesh(obj_path):
    """Run the full cut-and-LSCM pipeline for one OBJ file."""
    cs = ClosedSurface(str(obj_path))
    verts = cs.verts
    faces = cs.faces
    genus, chi, edge_count, boundary = mesh_genus(verts, faces)
    if boundary:
        raise RuntimeError("input mesh is not closed")

    cut_verts, cut_faces, new_to_old, basis, path_vertices = build_cut_disk(verts, faces, genus)
    cut_chi, cut_comps, loops = disk_checks(cut_verts, cut_faces)
    if cut_comps != 1 or len(loops) != 1 or cut_chi != 1:
        raise RuntimeError(
            f"cut failed: components={cut_comps}, boundary_loops={len(loops)}, chi={cut_chi}"
        )

    uv, fixed = solve_lscm(cut_verts, cut_faces, loops[0])
    if not np.all(np.isfinite(uv)):
        raise RuntimeError("LSCM produced non-finite UV coordinates")

    lap_colors = laplacian_magnitude_colors(verts, faces)
    quad_colors = quadrant_colors(verts)
    save_all_outputs(obj_path.stem, uv, cut_faces, new_to_old, lap_colors, quad_colors)

    print(f"{obj_path.name}:")
    print("  closed mesh:", len(verts), edge_count, len(faces), "chi", chi, "genus", genus)
    print("  cut mesh:", len(cut_verts), len(undirected_edges(cut_faces)[0]), len(cut_faces))
    print("  disk checks:", "components", cut_comps, "boundary_loops", len(loops), "chi", cut_chi)
    print("  fixed vertices:", fixed)
    if path_vertices:
        print("  genus-zero slit vertices:", len(path_vertices), "from", path_vertices[0], "to", path_vertices[-1])
    if basis:
        print("  homology lengths:", [round(x["length"], 6) for x in basis])
    print("  saved prefix:", str(OUTPUT_DIR / obj_path.stem))


def main():
    """Run the pipeline on closed genus-zero meshes and the genus-two example."""
    OUTPUT_DIR.mkdir(exist_ok=True)
    for obj_path in sorted(INPUT_DIR.glob("*.obj")):
        try:
            cs = ClosedSurface(str(obj_path))
            genus, chi, _, boundary = mesh_genus(cs.verts, cs.faces)
            if boundary or genus not in DEFAULT_GENERA:
                reason = "open mesh" if boundary else f"genus {genus}"
                print(f"{obj_path.name}: skipped by default ({reason})")
                continue
            process_mesh(obj_path)
        except Exception as exc:
            print(f"{obj_path.name}: skipped ({exc})")


if __name__ == "__main__":
    main()
